### ISSUE TITLE
[fcl 0.6.0] Segmentation fault in fcl::distance capsule-sphere 

### ISSUE THREAD

**Issue by wxmerkt** [flexible-collision-library/fcl#453]
I am running the 0.6.0 release on Ubuntu 18.04. My scene contains 3 capsules and 1 sphere. I get the following repeatable segmentation fault upon calling `fcl::distance` (in a deterministic optimisation). Sadly, I don't have transforms or other information to help reproduce right now :'(.

> 0x00007fffb6868662 in fcl::detail::GJKSolver_libccd<double>::S fcl::distance<fcl::detail::GJKSolver_libccd<double> >(fcl::CollisionGeometry<fcl::detail::GJKSolver_libccd<double>::S> const*, Eigen::Transform<fcl::detail::GJKSolver_libccd<double>::S, 3, 1, 0> const&, fcl::CollisionGeometry<fcl::detail::GJKSolver_libccd<double>::S> const*, Eigen::Transform<fcl::detail::GJKSolver_libccd<double>::S, 3, 1, 0> const&, fcl::detail::GJKSolver_libccd<double> const*, fcl::DistanceRequest<fcl::detail::GJKSolver_libccd<double>::S> const&, fcl::DistanceResult<fcl::detail::GJKSolver_libccd<double>::S>&) ()
>    from [path]/lib/libfcl.so.0.6
> 
> #0  0x00007fffb6868662 in fcl::detail::GJKSolver_libccd<double>::S fcl::distance<fcl::detail::GJKSolver_libccd<double> >(fcl::CollisionGeometry<fcl::detail::GJKSolver_libccd<double>::S> const*, Eigen::Transform<fcl::detail::GJKSolver_libccd<double>::S, 3, 1, 0> const&, fcl::CollisionGeometry<fcl::detail::GJKSolver_libccd<double>::S> const*, Eigen::Transform<fcl::detail::GJKSolver_libccd<double>::S, 3, 1, 0> const&, fcl::detail::GJKSolver_libccd<double> const*, fcl::DistanceRequest<fcl::detail::GJKSolver_libccd<double>::S> const&, fcl::DistanceResult<fcl::detail::GJKSolver_libccd<double>::S>&) ()
>    from [path]/lib/libfcl.so.0.6
> #1  0x00007fffb6868975 in double fcl::distance<double>(fcl::CollisionObject<double> const*, fcl::CollisionObject<double> const*, fcl::DistanceRequest<double> const&, fcl::DistanceResult<double>&) ()
>    from [path]/lib/libfcl.so.0.6

Similar to previous issues #407, #313

**Comment by wxmerkt** [comment]
Closing - While working on the reproduction case, I noticed that one of the transform contained NaNs.
